---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-local01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pradeepdevananth/argocd-poc.git
    targetRevision: HEAD
    path: environments/staging/app-01
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncPolicy:
      - Validate=true
      - CreateNamespaces=true
      - PrunePropagationPolicy=Foreground
      - PruneLast=true
